fix mingw test build
platform_deps is required to correctly link socket-test.exe

[141/148] Linking target tests/socket-test.exe.
FAILED: tests/socket-test.exe
i686-w64-mingw32-gcc  -o tests/socket-test.exe 'tests/59830eb@@socket-test@exe/socket-test.c.obj' -flto -Wl,-O1 -Wl,--start-group tests/libtest-utils.dll.a libsoup/libsoup-2.4.dll.a /usr/i686-w64-mingw32/lib/libintl.dll.a /usr/i686-w64-mingw32/lib/libglib-2.0.dll.a /usr/i686-w64-mingw32/lib/libgobject-2.0.dll.a /usr/i686-w64-mingw32/lib/libgio-2.0.dll.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -Wl,--end-group
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /tmp/cctFwrHy.ltrans0.ltrans.o:<artificial>:(.text+0x24): undefined reference to `_imp__htonl@4'
collect2: error: ld returned 1 exit status