meson: Explicitly link to libdl on non-Windows
Ever since commit 1296cbf9, building on older Linux such as Ubuntu
18.04 fails with:

```
subprojects/libsoup-3.6.5/libsoup/libsoup-3.0.so.0.7.4.p/soup-init.c.o: In function `soup_init_ctor':
soup-init.c:(.text.startup+0x24): undefined reference to `dlopen'
soup-init.c:(.text.startup+0x3c): undefined reference to `dlsym'
soup-init.c:(.text.startup+0x48): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
```

Responsible MR: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/475