Fix build with libxml2-2.12.0 and clang-17
Fixes build errors about missing function prototypes with clang-17

Fixes
| ../libsoup-2.74.3/libsoup/soup-xmlrpc-old.c:512:8: error: call to undeclared function 'xmlParseMemory'; ISO C99 and later do not support implicit function declarations

Signed-off-by: Khem Raj <raj.khem@gmail.com>